{
 "title": "Ratify",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "ratify pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"$namespace\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Verification RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(ratify_verification_request_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Count of Verifier Operations Per Interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(error, success, verifier) (increase(ratify_verifier_duration_count[$__rate_interval]))",
     "legendFormat": "verifier={{verifier}} isSuccess={{success}} isError={{error}}"
    }
   ]
  },
  {
   "title": "P95 Mutation Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (ratify_mutation_request_bucket))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95 Verification Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (ratify_verification_request_bucket))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blob Cache Hit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expression": "$B/($A+$B) * 100", "type": "math" }
   ]
  },
  {
   "title": "Registry Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(ratify_registry_request_count_total[$__rate_interval]))",
     "legendFormat": "non 429"
    },
    {
     "expr": "sum(increase(ratify_registry_request_count_total{status_code=\"429\"}[$__rate_interval]))",
     "legendFormat": "429"
    }
   ]
  },
  {
   "title": "Memory Usage (WSS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"\", namespace=\"$namespace\", pod=\"$pod\", container!=\"\", image!=\"\"}) by (container)",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", cluster=\"\", namespace=\"$namespace\", pod=\"$pod\", resource=\"memory\"}\n)\n",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", pod=\"$pod\", container=\"ratify\"}",
     "legendFormat": "ratify"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{namespace=\"$namespace\", pod=\"$pod\", resource=\"cpu\"}\n)\n",
     "legendFormat": "request"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{namespace=\"$namespace\", pod=\"$pod\", resource=\"cpu\"}\n)\n",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Error Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    { "expr": "ratify_system_error_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Azure",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "P95 AKV Certificate Fetch Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le) (ratify_akv_certificate_duration_bucket))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P95 AAD Exchange Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le) (ratify_aad_exchange_duration_bucket))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P95 ACR Exchange Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le) (ratify_acr_exchange_duration_bucket))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}